### ISSUE TITLE
[Feature Request] Swap some boolean for integers / floats

### ISSUE THREAD

**Issue by TiphaineLAURENT** [Max094Reikeb/NotEnoughGamerules#1]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Swap the boolean used for `dragonBreathDamage`, `explosionDamage`, `lightningDamage` and `naturalHunger` for integers / floats (-1 could be disable). The goal is to be able to change the specific value for this things, and not just enable/disable them.

**Describe alternatives you've considered**
None

**Additional context**
-

**Comment by Max094Reikeb** [comment]
Is it really possible to change the damages dealt by Dragon Breath or Lightning?

**Comment by TiphaineLAURENT** [comment]
I believe it is using mixins
