### ISSUE TITLE
disableInteractions gamerule

### ISSUE THREAD

**Issue by egdg5000** [Max094Reikeb/NotEnoughGamerules#21]
### Is your feature request related to a problem? Please describe.

When you have a server that runs a lobby with trapdoors or other redstone components it is really annoying when they get opened and closed all the time. 

### Describe the solution you'd like

Add a gamerule to disable player and/or mob interactions on trapdoors, doors, buttons, pressure plates, etc.

### Describe alternatives you've considered

None

**Comment by FirstMegaGame4** [comment]
Oh that's a really good idea i think
If the mod owner is ok with that, i can develop this gamerule
