### ISSUE TITLE
[1.18.2] Crash On Startup

### ISSUE THREAD

**Issue by qznfbnj** [Max094Reikeb/NotEnoughGamerules#23]
### Describe the Bug

Crash On Startup

### To Reproduce

1.install forge 40.1.0
2.install NEG-FORGE-1.18.2-r1.4.1.jar
3.startup and crash

### Expected Behavior

game crash before loading screen appear

### Screenshots

![neg-crash](https://user-images.githubusercontent.com/100760086/166108347-ce940b05-9463-4210-8b00-c1aa70236d00.jpg)

### Mod Version

1.4.1

### Minecraft Version

1.18.1

### Forge Version

40.1.0

### Additional Context

[minecraft-exported-crash-info-2022-04-30T21-19-32.zip](https://github.com/Max094Reikeb/NotEnoughGamerules/files/8597020/minecraft-exported-crash-info-2022-04-30T21-19-32.zip)
[if delete "blocks.ChangeBlockMixin" in not_enough_gamerules.mixins.json, game can start, then crash happen on clicking single player button]

**Comment by Max094Reikeb** [comment]
Issue fixed with commit d676eade3b09d63a4c6aa052d1a5f8025d3689ff
