### ISSUE TITLE
Compatibility with mod Guard Villager

### ISSUE THREAD

**Issue by GoldenTotem** [Max094Reikeb/NotEnoughGamerules#26]
### Describe the Bug

If doTransformations is set to false, villagers will not be transformed to witches or zombie villagers, but guards in Guard Villager(https://www.curseforge.com/minecraft/mc-mods/guard-villagers) will still be transformed.

### To Reproduce

Set doTransformations to false and let guards hit by lightning

### Expected Behavior

I hope that this mod is compatible with other mods, maybe it's not easy.

### Mod Version

1.4

### Minecraft Version

1.16.5

### Forge Version

36.2.39

**Comment by Max094Reikeb** [comment]
Issue is now fixed!
