### ISSUE TITLE
wrong cast with Mana and Artifice

### ISSUE THREAD

**Issue by x4dr** [Max094Reikeb/NotEnoughGamerules#27]
### Describe the Bug

class com.mna.entities.faction.WitchHunterArrow cannot be cast to class net.minecraft.world.entity.LivingEntity 
https://bytebin.lucko.me/9aXBAwGizL
https://crashy.net/I7O1VQzWjgchE30IOVk6

### To Reproduce

have mana and artifice installed
randomly when witchhunters shoot the game will crash

### Expected Behavior

game does not crash

### Mod Version

1.4.2

### Minecraft Version

1.18.2

### Forge Version

40.1.84

**Comment by Max094Reikeb** [comment]
The issue is from the mod itself. The arrow should be a LivingEntity, I don't know why it isn't. Please report this bug to their bug report tracker.
