### ISSUE TITLE
ClassCastException with IAF EntityStymphalianFeather

### ISSUE THREAD

**Issue by Kasualix** [Max094Reikeb/NotEnoughGamerules#33]
### Describe the Bug

https://github.com/Max094Reikeb/NotEnoughGamerules/blob/22206679754dabedbe45949f807d6f56b327cb36/src/main/java/net/reikeb/not_enough_gamerules/events/PlayerHurtEvent.java#L22
A "instanceof" check if may be required.
Or just "Entity sourceentity = event.getSource().getEntity()"

### To Reproduce

...

### Expected Behavior

...

### Mod Version

1.4.2

### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Additional Context

crash report: https://pastebin.ubuntu.com/p/BPsQkq7mXX/
Just see https://github.com/Max094Reikeb/NotEnoughGamerules/issues/27, and I cannot understand why, in my opinion this is all your fault, because we can never guess whether or not other mods use the right implementation, isn't that the point of instanceof's existence?

**Comment by Max094Reikeb** [comment]
1.19.2 and below are deprecated. It is advised to use 1.19.3 and above (1.19.4 and 1.20 are coming soon)
