### ISSUE TITLE
[1.18.2] Crash during gameplay. Caused by: not_enough_gamerules.events.PlayerHurtEvent.onEntityAttacked

### ISSUE THREAD

**Issue by Delfite** [Max094Reikeb/NotEnoughGamerules#34]
### Describe the Bug

I was fighting a group of pillagers at a pillager outpost, I jumped into a pool of water to chase one of them down. Mere moments after I killed the pillager I was chasing, the game froze for a few seconds and crashed to desktop.

Crash Report: https://gnomebot.dev/paste/1118030411700912198
Do not tell me or ask me to use another paste site, this one works just fine.

### To Reproduce

1. Download all the mods listed in the crash report.
2. Launch the game.
3. Create a new world in Survival mode with Cheats enabled.
4. Get pelted with a bunch of arrows by some pillagers.
5. Uh, I guess just wait for the crash to happen like it did for me. No idea how to reproduce it beyond that sadly.

### Expected Behavior

I shouldn't have crashed seemingly out of nowhere.

### Mod Version

1.4.2

### Minecraft Version

1.18.2

### Forge Version

40.2.9 (Current Latest)

### Additional Context

Question: Why is there nowhere on the form to put the latest.log or crash report related to the issue? Those files are INTEGRAL to debugging issues with your mod(s)!

**Comment by Max094Reikeb** [comment]
Sorry but 1.18.2 version isn't being worked on. Use the latest 1.19 versions, as it is recommended.

**Comment by Delfite** [comment]
> Sorry but 1.18.2 version isn't being worked on. Use the latest 1.19 versions, as it is recommended.

1.18.2 has mods like Immersive Petroleum, 1.19+ does not.

In conclusion: No thanks. I'd rather have my Pumpjacks and Distillation Towers instead of not having them at all. I'll be disabling your mod until this crash is fixed by someone.

**Comment by Delfite** [comment]
> In conclusion: No thanks. I'd rather have my Pumpjacks and Distillation Towers instead of not having them at all. I'll be disabling your mod until this crash is fixed by someone.

Thinking back on this now, that sounded really passive-aggressive, though then again I don't remember having a very good day at the time so that might be why.
