### ISSUE TITLE
Implement commandBlocksEnabled from Bedrock Edition

### ISSUE THREAD

**Issue by z0ok3difficult** [Max094Reikeb/NotEnoughGamerules#36]
### Is your feature request related to a problem? Please describe.

Currently, in the Java Edition of Minecraft, there is no direct equivalent of the "commandBlocksEnabled" gamerule found in the Bedrock Edition. This gamerule allows players to enable or disable the usage of command blocks in their worlds. However, since this gamerule is missing in Java Edition, players are unable to have the same level of control over command block usage.

### Describe the solution you'd like

I would like to suggest implementing the "commandBlocksEnabled" gamerule in the mod. This feature would provide players with the ability to enable or disable command blocks in their Minecraft worlds, similar to how it functions in the Bedrock Edition.

### Describe alternatives you've considered

?

**Comment by FirstMegaGame4** [comment]
This feature is included in your server's server.properties file, and is not necessary for client's worlds.

**Comment by Max094Reikeb** [comment]
Indeed, there is no need for it
