### ISSUE TITLE
"modmenu" thinks the mod need's an update when it doesn't.

### ISSUE THREAD

**Issue by Ocraftj** [Max094Reikeb/NotEnoughGamerules#40]
### Describe the Bug

i have vr1.5.3, but it says that's the update

### To Reproduce

1. download mod menu
2. download NEG (newest version)
3. check if the mod needs an update
4. it needs an update even though it's the newest version.

### Expected Behavior

it not need to be updated

### Screenshots

![Screenshot (260)](https://github.com/Max094Reikeb/NotEnoughGamerules/assets/100333726/2af65f5c-5050-446a-88a2-53859bc2dae9)

### Mod Version

1.5.3

### Minecraft Version

1.20.1

### Fabric Loader Version

0.14.21

### Fabric API Version

0.85.0

### Additional Context

newest version of farbric, fabric api, and mod menu

**Comment by Ocraftj** [comment]
i'm not sure if it's because of file naming but it's pretty annoying.

**Comment by Ocraftj** [comment]
i think it's because on modrinth there are 2 different files for the same section of the mod, one for 1.19.4 and one for 1.20.1

**Comment by FirstMegaGame4** [comment]
Is that really a NEG-Fabric issue ? ModMenu itself says that its update checker is experimental. I think this issue should be reported on the ModMenu issue tracker, don't you ?

**Comment by FirstMegaGame4** [comment]
But there is also a chance this bug comes from the weird NEG versionning system, in which case it's not ModMenu's fault. NEG will change his mod loader supports soon and his versionning sytem will change at the same time.

**Comment by Ocraftj** [comment]
ok cool
